name: EAS build Android
on:
  push:
    branches:
      - production/android

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Use google cloud key file from secrets
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          filename: "valor-rpm-gcloud-key.json"
          is-executable: false

      - name: Install dependencies
        run: npm i

      - name: Build on EAS
        run: npm run expo-build-ci-android